### ISSUE TITLE
关于混合检索的问题

### ISSUE THREAD

**Issue by tuqingwen** [Chocolate-Black/Langchain-MO-AI-Chat#2]
![1716641240497](https://github.com/Chocolate-Black/Langchain-MO-AI-Chat/assets/103909737/dc77603c-0039-4c2b-8c65-8769b15630b0)
这里的do_seach函数设置的分数似乎不合理，博主考虑使用倒数融合排序（rrf）吗？

**Comment by nilin1998** [comment]
> ![1716641240497](https://private-user-images.githubusercontent.com/103909737/333800692-dc77603c-0039-4c2b-8c65-8769b15630b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NTQ4NTksIm5iZiI6MTcxNjk1NDU1OSwicGF0aCI6Ii8xMDM5MDk3MzcvMzMzODAwNjkyLWRjNzc2MDNjLTAwMzktNGMyYi04YzY1LTg3NjliMTU2MzBiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQwMzQ5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDM1NzdiNzdlNWIxYWI0NDk1MmE4Yzk3ZjZmMmIzNzkzNzlhZDI3ZmIyZTlkODgxYjI5NjljOWJhZWNiYmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V96h4Hz0-DbFauETKh6lkXipLi0BrjFQbOGgmerJaCU) 这里的do_seach函数设置的分数似乎不合理，博主考虑使用倒数融合排序（rrf）吗？
您好，我想问一下我在创建向量库时，已经成功执行了bm25_kb_service里面的初始化函数，里面的文件数量等均不为0了，但是我后续通过chat模式，调用kb_doc_api文件的do_search，再调用bm25的search函数时，发现文件数量又均为0了，请问您遇到过这种现象嘛，怎么解决的呀

**Comment by Jieszs** [comment]
> ![1716641240497](https://private-user-images.githubusercontent.com/103909737/333800692-dc77603c-0039-4c2b-8c65-8769b15630b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzExNTAsIm5iZiI6MTcyMjkzMDg1MCwicGF0aCI6Ii8xMDM5MDk3MzcvMzMzODAwNjkyLWRjNzc2MDNjLTAwMzktNGMyYi04YzY1LTg3NjliMTU2MzBiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwNzU0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMGVmY2ZlZWYwZDk4ZWMxZGY0ZTdiNjM4ZjJmZTA5YTcxOTU3ZjMwODg5MTcwN2QwN2JjMDEzM2FmOTBmMmExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.soPVYxeXOsUTYZ6i8ofIW30pVqjIo6CjVjTAUcnEVTA) 这里的do_seach函数设置的分数似乎不合理，博主考虑使用倒数融合排序（rrf）吗？

我用了倒数融合排序（rrf），没有实际的应用场景和知识库文件，感觉不出来有什么区别，而且你也知道设置BM25 和faiss的权重适合多少。
我是挺想知道，作者的这个分数设置是哪里来的，有没有理论依据

**Comment by Chocolate-Black** [comment]
> > ![1716641240497](https://private-user-images.githubusercontent.com/103909737/333800692-dc77603c-0039-4c2b-8c65-8769b15630b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzExNTAsIm5iZiI6MTcyMjkzMDg1MCwicGF0aCI6Ii8xMDM5MDk3MzcvMzMzODAwNjkyLWRjNzc2MDNjLTAwMzktNGMyYi04YzY1LTg3NjliMTU2MzBiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwNzU0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMGVmY2ZlZWYwZDk4ZWMxZGY0ZTdiNjM4ZjJmZTA5YTcxOTU3ZjMwODg5MTcwN2QwN2JjMDEzM2FmOTBmMmExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.soPVYxeXOsUTYZ6i8ofIW30pVqjIo6CjVjTAUcnEVTA) 这里的do_seach函数设置的分数似乎不合理，博主考虑使用倒数融合排序（rrf）吗？
> 
> 我用了倒数融合排序（rrf），没有实际的应用场景和知识库文件，感觉不出来有什么区别，而且你也知道设置BM25 和faiss的权重适合多少。 我是挺想知道，作者的这个分数设置是哪里来的，有没有理论依据

RRF更适合一些。可以不用参考我的分数设置，当时是为了做测试先随便设置的。后续忘了把那部分改过来了。
